"""initial schema

Revision ID: 0d470cb9f644
Revises: 
Create Date: 2026-09-27 17:20:00.404280

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d470cb9f644'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer', sa.String(length=300), nullable=False),
    sa.Column('ats', sa.String(length=50), nullable=False),
    sa.Column('tenant_key', sa.String(length=300), nullable=False),
    sa.Column('career_site_origin', sa.String(length=300), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.Column('credential_reference', sa.String(length=200), nullable=False),
    sa.Column('account_status', sa.String(length=30), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_successful_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_accounts_ats'), ['ats'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_accounts_tenant_key'), ['tenant_key'], unique=True)

    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_urls', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_profiles_email'), ['email'], unique=False)

    op.create_table('extension_pairings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('extension_origin', sa.String(length=200), nullable=False),
    sa.Column('paired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extension_pairings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extension_pairings_token_hash'), ['token_hash'], unique=True)

    op.create_table('field_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ats', sa.String(length=50), nullable=False),
    sa.Column('normalized_label', sa.String(length=300), nullable=False),
    sa.Column('dom_signature', sa.String(length=500), nullable=False),
    sa.Column('canonical_field', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('last_validated_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_mappings_ats'), ['ats'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_job_key', sa.String(length=128), nullable=False),
    sa.Column('ats', sa.String(length=50), nullable=True),
    sa.Column('external_job_id', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('normalized_company', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('normalized_title', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('remote_type', sa.String(length=30), nullable=True),
    sa.Column('salary', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_hash', sa.String(length=64), nullable=True),
    sa.Column('canonical_application_url', sa.String(length=1000), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_ats'), ['ats'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_canonical_job_key'), ['canonical_job_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_jobs_normalized_company'), ['normalized_company'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_normalized_title'), ['normalized_title'], unique=False)

    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('output_validation_status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_question', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_mappings_normalized_question'), ['normalized_question'], unique=True)

    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('titles', sa.JSON(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('hybrid', sa.Boolean(), nullable=False),
    sa.Column('onsite', sa.Boolean(), nullable=False),
    sa.Column('salary_minimum', sa.Float(), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('desired_seniority', sa.JSON(), nullable=False),
    sa.Column('excluded_titles', sa.JSON(), nullable=False),
    sa.Column('excluded_employers', sa.JSON(), nullable=False),
    sa.Column('excluded_industries', sa.JSON(), nullable=False),
    sa.Column('required_keywords', sa.JSON(), nullable=False),
    sa.Column('preferred_keywords', sa.JSON(), nullable=False),
    sa.Column('travel_preference', sa.String(length=50), nullable=True),
    sa.Column('relocation_willingness', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('answer_key', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('explanatory_text', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(length=100), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_answers_answer_key'), ['answer_key'], unique=False)

    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('certification', sa.String(length=300), nullable=False),
    sa.Column('issuer', sa.String(length=300), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=300), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('field', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('employer', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('source_resume_id', sa.String(length=64), nullable=True),
    sa.Column('original_resume_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('local_path', sa.String(length=1000), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('template_version', sa.String(length=20), nullable=False),
    sa.Column('source_claim_ids', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('hard_filter_result', sa.String(length=20), nullable=False),
    sa.Column('required_coverage', sa.Float(), nullable=False),
    sa.Column('preferred_score', sa.Float(), nullable=False),
    sa.Column('domain_alignment', sa.Float(), nullable=False),
    sa.Column('seniority_alignment', sa.Float(), nullable=False),
    sa.Column('preference_alignment', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('disqualifiers', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('evaluation_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('normalized_requirement', sa.String(length=500), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_source_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('canonical_skill', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('candidate_confirmed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_canonical_skill'), ['canonical_skill'], unique=False)

    op.create_table('verified_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('employer', sa.String(length=300), nullable=True),
    sa.Column('associated_role', sa.String(length=300), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('source_document', sa.String(length=300), nullable=True),
    sa.Column('source_section', sa.String(length=200), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verified_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verified_claims_category'), ['category'], unique=False)

    op.create_table('voluntary_disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('disclosure_key', sa.String(length=100), nullable=False),
    sa.Column('response_mode', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=30), nullable=False),
    sa.Column('submission_mode', sa.String(length=20), nullable=False),
    sa.Column('adapter', sa.String(length=50), nullable=True),
    sa.Column('adapter_version', sa.String(length=20), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_id', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=100), nullable=True),
    sa.Column('resume_document_id', sa.Integer(), nullable=True),
    sa.Column('confirmation_id', sa.String(length=200), nullable=True),
    sa.Column('final_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_document_id'], ['generated_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_lease_id'), ['lease_id'], unique=False)

    op.create_table('application_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.String(length=500), nullable=True),
    sa.Column('answer_category', sa.String(length=50), nullable=True),
    sa.Column('answer_submitted', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('claim_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('user_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('adapter_state', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_events')
    op.drop_table('application_answers')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_lease_id'))

    op.drop_table('applications')
    op.drop_table('voluntary_disclosures')
    with op.batch_alter_table('verified_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verified_claims_category'))

    op.drop_table('verified_claims')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_canonical_skill'))

    op.drop_table('skills')
    op.drop_table('job_sources')
    op.drop_table('job_requirements')
    op.drop_table('job_evaluations')
    op.drop_table('generated_documents')
    op.drop_table('employment_history')
    op.drop_table('education')
    op.drop_table('certifications')
    with op.batch_alter_table('candidate_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_answers_answer_key'))

    op.drop_table('candidate_answers')
    op.drop_table('search_profiles')
    with op.batch_alter_table('question_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_mappings_normalized_question'))

    op.drop_table('question_mappings')
    op.drop_table('model_runs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_jobs_normalized_company'))
        batch_op.drop_index(batch_op.f('ix_jobs_canonical_job_key'))
        batch_op.drop_index(batch_op.f('ix_jobs_ats'))

    op.drop_table('jobs')
    with op.batch_alter_table('field_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_mappings_ats'))

    op.drop_table('field_mappings')
    with op.batch_alter_table('extension_pairings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_pairings_token_hash'))

    op.drop_table('extension_pairings')
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_email'))

    op.drop_table('candidate_profiles')
    with op.batch_alter_table('candidate_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_accounts_tenant_key'))
        batch_op.drop_index(batch_op.f('ix_candidate_accounts_ats'))

    op.drop_table('candidate_accounts')
    op.drop_table('automation_state')
    # ### end Alembic commands ###
