"""add target employers

Revision ID: e47b5397b5cc
Revises: 0d470cb9f644
Create Date: 2026-09-27 18:56:24.180381

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e47b5397b5cc'
down_revision: Union[str, None] = '0d470cb9f644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('ats', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_status', sa.String(length=30), nullable=True),
    sa.Column('last_check_error', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target_employers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_employers_ats'), ['ats'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('target_employers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_employers_ats'))

    op.drop_table('target_employers')
    # ### end Alembic commands ###
